package models

import (
	"time"

	"github.com/uptrace/bun"
)

const (
	AssetStatusPending    = "pending"
	AssetStatusProcessing = "processing"
	AssetStatusReady      = "ready"
	AssetStatusPartial    = "partial"
	AssetStatusFailed     = "failed"
)

const (
	// AssetTypeMarkdown marks assets imported from a `.md` upload.
	AssetTypeMarkdown = "MD"
	// AssetTypePDF marks assets imported from a `.pdf` upload.
	AssetTypePDF = "PDF"
	// AssetTypeURL marks assets scraped from a web page URL (CON-222).
	AssetTypeURL = "URL"
	// AssetTypeImage marks assets that are an uploaded image (CON-246). Its
	// content is a plain-text description, not a document; empty is valid.
	AssetTypeImage = "IMG"
	// AssetTypeDocument marks assets imported from an office/text document upload
	// parsed by document-service (CON-280): .docx/.pptx/.xlsx/.odt/.ods/.odp/
	// .epub/.csv/.tsv/.html/.xhtml/.eml/.rtf/.txt/.log. The specific format is
	// recorded in asset_files.mime_type; assets.type stays a coarse enum.
	AssetTypeDocument = "DOC"
	// AssetTypeAudio marks assets imported from an audio upload transcribed by
	// audio-service (CON-282): mp3/wav/aac-m4a/ogg-opus/flac/webm/aiff. The
	// specific format is recorded in asset_files.mime_type; the searchable
	// content is the assembled transcript, chunked with time-range anchors.
	AssetTypeAudio = "AUDIO"
)

type Asset struct {
	bun.BaseModel `bun:"table:assets,alias:a" swaggerignore:"true"`
	TenantScoped  // CON-97: tenant_id column + central scoping hooks

	ID      string  `bun:"id,pk"                                        json:"id"`
	Title   string  `bun:"title,notnull"                                json:"title"`
	Content string  `bun:"content,notnull"                              json:"content"`
	Status  string  `bun:"status,notnull,default:'ready'"               json:"status"`
	Type    *string `bun:"type"                                         json:"type"`
	// SourceURL is the origin URL for URL-scraped assets (CON-222); nil for
	// MD/PDF/text assets. Unique per tenant, so re-submitting a URL refreshes
	// the same asset instead of duplicating it.
	SourceURL *string `bun:"source_url"                                   json:"source_url,omitempty"`
	// AltText is a short accessibility description for image assets (CON-246),
	// distinct from content (the longer, embeddable description). Empty for
	// non-image assets. For images it is auto-generated by image-service unless a
	// user has edited it (CON-281, see AltTextEditedByUser).
	AltText string `bun:"alt_text,notnull,default:''"                  json:"alt_text"`
	// AltTextEditedByUser guards a user's manual alt text from being overwritten
	// by (re-)processing (CON-281 D5): image-service fills AltText only while this
	// is false; a PUT that sets alt_text flips it true, so re-extraction never
	// clobbers a human edit.
	AltTextEditedByUser bool        `bun:"alt_text_edited_by_user,notnull,default:false" json:"alt_text_edited_by_user"`
	TagIDs              StringSlice `bun:"tag_ids,notnull,type:jsonb"                   json:"tag_ids"`
	Tags                []Tag       `bun:"-"                                            json:"tags"`
	File                *AssetFile  `bun:"-"                                            json:"file,omitempty"`
	// Images are the mirrored page images for URL assets (CON-222), hydrated and
	// URL-decorated by the handler layer. Not persisted on assets.
	Images    []AssetImage `bun:"-" json:"images,omitempty"`
	CreatedBy string       `bun:"created_by,notnull"                           json:"created_by"`
	CreatedAt time.Time    `bun:"created_at,notnull,default:current_timestamp" json:"created_at"`
	UpdatedAt time.Time    `bun:"updated_at,notnull,default:current_timestamp" json:"updated_at"`
}
