package models

import (
	"time"

	"github.com/uptrace/bun"
)

type PostAttachment struct {
	bun.BaseModel `bun:"table:post_attachments,alias:pa" swaggerignore:"true"`
	TenantScoped  // CON-97: tenant_id column + central scoping hooks

	ID       string `bun:"id,pk"                                        json:"id"`
	PostID   string `bun:"post_id,notnull"                              json:"post_id"`
	Position int    `bun:"position,notnull"                             json:"position"`
	// SegmentIndex names which message of a threaded post this attachment
	// belongs to (CON-284), 0-based into Post.ThreadSegments. NULL for every
	// attachment of a non-thread post — it belongs to the whole/single post,
	// today's behaviour. Within a segment, Position still orders the media. A
	// pointer so nil ⇔ NULL is distinct from a valid segment 0.
	SegmentIndex *int `bun:"segment_index"                                json:"segment_index"`
	// AltText is the accessibility description for the media (CON-122). Empty
	// means "no alt text". Editable on upload and via PATCH; sent to Zernio as
	// mediaItems[].altText. For images it is auto-generated by image-service
	// (CON-281) unless a user has supplied/edited it (see AltTextEditedByUser).
	AltText string `bun:"alt_text,notnull,default:''"                  json:"alt_text"`
	// AltTextEditedByUser guards a user's alt text from being overwritten by
	// async auto-generation (CON-281 D5): the generator fills AltText only while
	// this is false; a user-supplied alt_text on upload or a PATCH sets it true.
	AltTextEditedByUser bool   `bun:"alt_text_edited_by_user,notnull,default:false" json:"alt_text_edited_by_user"`
	MimeType            string `bun:"mime_type,notnull"                            json:"mime_type"`
	SizeBytes           int64  `bun:"size_bytes,notnull"                           json:"size_bytes"`
	Width               int    `bun:"width,notnull"                                json:"width"`
	Height              int    `bun:"height,notnull"                                json:"height"`
	IsAnimated          bool   `bun:"is_animated,notnull"                          json:"is_animated"`
	PageCount           int    `bun:"page_count,notnull"                           json:"page_count"`
	// DurationMs and Codec carry video metadata probed by video-service
	// (CON-148). Zero/empty for non-video attachments and when the probe
	// is unavailable (graceful degradation). Width/Height are reused for
	// the video's frame size.
	DurationMs     int64     `bun:"duration_ms,notnull,default:0" json:"duration_ms"`
	Codec          string    `bun:"codec,notnull,default:''"      json:"codec"`
	ChecksumSHA256 string    `bun:"checksum_sha256,notnull"                      json:"checksum_sha256"`
	S3Key          string    `bun:"s3_key,notnull"                               json:"s3_key"`
	ThumbnailS3Key string    `bun:"thumbnail_s3_key"                             json:"thumbnail_s3_key,omitempty"`
	CreatedBy      string    `bun:"created_by,notnull"                           json:"created_by"`
	CreatedAt      time.Time `bun:"created_at,notnull,default:current_timestamp" json:"created_at"`

	// PresignedURL and ThumbnailURL are hydrated by the handler at
	// response time; they are not stored in the database.
	PresignedURL string `bun:"-" json:"presigned_url,omitempty"`
	ThumbnailURL string `bun:"-" json:"thumbnail_url,omitempty"`
}
